### ISSUE TITLE
makefile missing a rule for `athenb_hidden`

### ISSUE THREAD

**Issue by rgommers** [gillins/symbols_check#1]
Just trying on Linux, and `make` isn't happy. I assume this was the intent, and it got lost somehow:
```diff
+athenb_hidden: athenb.o
+       $(CC) -o athenb_hidden athenb.o scipy_a_hidden.so scipy_b.so -Wl,-rpath .
+
```

**Comment by gillins** [comment]
Sorry, shouldn't code on Friday afternoon! Fixed by https://github.com/gillins/symbols_check/commit/68ca14d6787e30cf0515074bc8b78c2059decea0
